name: healthcare-insurer-va
type: virtual-account
permissions:
  - resource_fqn: slayzsloth:openai:openai
    resource_type: provider-account
    role_id: provider-account-access
  - resource_fqn: slayzsloth:anthropic:anthropic
    resource_type: provider-account
    role_id: provider-account-access
tags:
  customer: healthcare-insurer
  compliance: soc2
  team: platform
  tier: enterprise
