type: virtual-account
name: bigcorp
permissions:
  - resource_type: provider-account
    resource_fqn: "slayzsloth:openai:openai"
    role_id: provider-account-access
  - resource_type: provider-account
    resource_fqn: "slayzsloth:anthropic:anthropic"
    role_id: provider-account-access
tags:
  customer: bigcorp
  tier: enterprise
  owner: atlas-platform-team
