name: atlas-cluster
cluster_type: aws-eks
environment_names:
  - prod
collaborators:
  - role_id: cluster-admin
    subject: user:gouravsingal2003@gmail.com
type: cluster
ingress_controller_config:
  ingress_class_name: istio
  tls_enabled: false
base_domains:
  - 13.202.247.205.nip.io
default_registry_fqn: slayzsloth:aws:atlas-cluster:docker-registry:registry
cluster_integration_fqn: slayzsloth:aws:atlas-cluster:cluster:cluster-integration
